//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaborAcielo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int id_produ { get; set; }
        public int id_tipoProdu { get; set; }
        public string nombre_produ { get; set; }
        public string detalle { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> stock { get; set; }
        public bool estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual Tipo_produ Tipo_produ { get; set; }
    }
}
